// options for dropdowns
export const locationOptions = [
      { label: 'New York', value: 'new york' },
      { label: 'Los Angeles', value: 'los angeles' },
      { label: 'Chicago', value: 'chicago' },
      { label: 'Houston', value: 'houston' },
      { label: 'Phoenix', value: 'phoenix' },
      { label: 'Philadelphia', value: 'philadelphia' },
      { label: 'San Antonio', value: 'san antonio' },
      { label: 'San Diego', value: 'san diego' },
      { label: 'Dallas', value: 'dallas' },
      { label: 'San Jose', value: 'san jose' },
];

export const priceOptions = [
      { label: '$50 - $200', value: '50-200' },
      { label: '$200 - $500', value: '200-500' },
      { label: '$500 - $1,000', value: '500-1000' },
      { label: '$1,000 - $2,500', value: '1000-2500' },
      { label: '$2,500 - $5,000', value: '2500-5000' },
      { label: '$5,000 - $7,500', value: '5000-7500' },
      { label: '$7,500 - $10,000', value: '7500-10000' },
      { label: '$10,000 - $15,000', value: '10000-15000' },
];

export const practiceTypeOptions = [
      { label: 'Dental Care', value: 'dental care' },
      { label: 'Eye Care', value: 'eye care' },
      { label: 'Primary Care', value: 'primary care' },
      { label: 'Pediatrics', value: 'pediatrics' },
      { label: 'Orthopedics', value: 'orthopedics' },
      { label: 'Dermatology', value: 'dermatology' },
      { label: 'Cardiology', value: 'cardiology' },
      { label: 'Oncology', value: 'oncology' },
      { label: 'Physical Therapy', value: 'physical therapy' },
      { label: 'Psychiatry', value: 'psychiatry' },
];

export const practiceNeedOptions = [
      { value: 'consultation', label: 'Consultation' },
      { value: 'surgery', label: 'Surgery' },
      { value: 'therapy', label: 'Therapy' },
      { value: 'diagnostics', label: 'Diagnostics' },
      { value: 'imaging', label: 'Imaging' },
      { value: 'emergency_care', label: 'Emergency Care' },
];

export const facilitiesOptions = [
      { label: 'Exam rooms', value: 'Exam rooms' },
      { label: 'Consultation rooms', value: 'Consultation rooms' },
      { label: 'Procedure rooms', value: 'Procedure rooms' },
      { label: 'Minor surgical suite', value: 'Minor surgical suite' },
      { label: 'Recovery room', value: 'Recovery room' },
      { label: 'Imaging facilities (e.g., X-ray, ultrasound)', value: 'Imaging facilities (e.g., X-ray, ultrasound)' },
      { label: 'Digital X-ray suite', value: 'Digital X-ray suite' },
      { label: 'Portable X-ray unit', value: 'Portable X-ray unit' },
      { label: 'Lead-lined walls for radiation safety', value: 'Lead-lined walls for radiation safety' },
      {
            label: 'PACS (Picture Archiving and Communication System)',
            value: 'PACS (Picture Archiving and Communication System)',
      },
      { label: 'Fluoroscopy unit', value: 'Fluoroscopy unit' },
      { label: 'C-arm machine', value: 'C-arm machine' },
      { label: 'DEXA scanner for bone density imaging', value: 'DEXA scanner for bone density imaging' },
      { label: 'Laboratory services', value: 'Laboratory services' },
      { label: 'Vaccination clinic setup', value: 'Vaccination clinic setup' },
      { label: 'Infusion therapy room', value: 'Infusion therapy room' },
      { label: 'Allergy testing and treatment room', value: 'Allergy testing and treatment room' },
      { label: 'Wound care room', value: 'Wound care room' },
      { label: 'Pulmonary function testing lab', value: 'Pulmonary function testing lab' },
      { label: 'Endoscopy suite', value: 'Endoscopy suite' },
      {
            label: 'Cardiology testing facilities (e.g., stress testing, echocardiography)',
            value: 'Cardiology testing facilities (e.g., stress testing, echocardiography)',
      },
      {
            label: 'Dermatology treatment area (e.g., laser or cosmetic equipment)',
            value: 'Dermatology treatment area (e.g., laser or cosmetic equipment)',
      },
      {
            label: 'OB/GYN-specific facilities (e.g., ultrasound, colposcopy equipment)',
            value: 'OB/GYN-specific facilities (e.g., ultrasound, colposcopy equipment)',
      },
      { label: 'Physical therapy space', value: 'Physical therapy space' },
      { label: 'Occupational therapy facilities', value: 'Occupational therapy facilities' },
      { label: 'Chiropractic adjustment room', value: 'Chiropractic adjustment room' },
      { label: 'Acupuncture or alternative medicine space', value: 'Acupuncture or alternative medicine space' },
      { label: 'Sleep study rooms', value: 'Sleep study rooms' },
      { label: 'Dialysis center', value: 'Dialysis center' },
      { label: 'Vision testing area', value: 'Vision testing area' },
      { label: 'Audiology testing booth', value: 'Audiology testing booth' },
      {
            label: 'Holter monitor and ambulatory blood pressure monitoring equipment',
            value: 'Holter monitor and ambulatory blood pressure monitoring equipment',
      },
      { label: 'Cleanroom for sterile compounding', value: 'Cleanroom for sterile compounding' },
      { label: 'On-site pharmacy', value: 'On-site pharmacy' },
      { label: 'Sterilization area', value: 'Sterilization area' },
      { label: 'Medical supply storage', value: 'Medical supply storage' },
      { label: 'Break room', value: 'Break room' },
      { label: 'Conference or meeting rooms', value: 'Conference or meeting rooms' },
      { label: 'Patient education rooms', value: 'Patient education rooms' },
      { label: 'Waiting area', value: 'Waiting area' },
      { label: 'Reception and administrative support', value: 'Reception and administrative support' },
      { label: 'Handicap accessibility features', value: 'Handicap accessibility features' },
      { label: 'Shared utilities (electricity, water, HVAC)', value: 'Shared utilities (electricity, water, HVAC)' },
      { label: 'High-speed internet and IT support', value: 'High-speed internet and IT support' },
      { label: 'Telemedicine equipment', value: 'Telemedicine equipment' },
      { label: 'Security and surveillance systems', value: 'Security and surveillance systems' },
      { label: 'Billing and coding services', value: 'Billing and coding services' },
      { label: 'EMR (Electronic Medical Records) systems', value: 'EMR (Electronic Medical Records) systems' },
      { label: 'Parking facilities', value: 'Parking facilities' },
];
